name: Deploy data pipeline

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: "quickstart_common.public.quickstart_repo"
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      # Checkout repository to access SQL files in steps folder
      - name: Checkout repository
        uses: actions/checkout@v4

      # Manually install Snowflake CLI in a virtual environment with dependencies
      - name: Install Snowflake CLI with dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install snowflake-cli-labs --upgrade --include-deps

      # Verify Snowflake CLI installation
      - name: Verify Snowflake CLI installation
        run: |
          source venv/bin/activate
          snow --version

      # Fetch repository changes from Snowflake Git Repo
      - name: Fetch repository changes
        run: |
          source venv/bin/activate
          snow git fetch "${REPO_NAME}"

      # Deploy pipeline by executing the steps in the deploy_parametrized_pipeline.sql file
      - name: Deploy data pipeline
        run: |
          source venv/bin/activate
          BRANCH_NAME=${{ github.ref_name }}
          snow git execute \
            "@${REPO_NAME}/branches/${BRANCH_NAME}/deploy_parametrized_pipeline.sql"
