name: Deploy Data Pipeline

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: "snowlab.public.git_repo_test"
      # Read connection secrets
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      # Checkout step to use a config file from the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Snowflake CLI GitHub Action and point to config file
      - uses: Snowflake-Labs/snowflake-cli-action@v1
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      # Debug: Check Snowflake CLI installation
      - name: Check Snowflake CLI version
        run: snow --version

      # Update Snowflake's copy of the repository
      - name: Fetch repository changes
        run: snow git fetch "${REPO_NAME}"

      # Debug: List contents of repository to ensure the file exists
      - name: List repository contents
        run: snow git ls "${REPO_NAME}/branches/main"

      # Deploy data pipeline by executing the SQL file
      - name: Deploy data pipeline
        run: |
          BRANCH_NAME=main
          # Execute the SQL file from the repository
          snow git execute "@${REPO_NAME}/branches/main/deploy_parametrized_pipeline.sql"
