name: Deploy data pipeline

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: "quickstart_common.public.quickstart_repo"
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_WAREHOUSE: "QUICKSTART_WH" # Warehouse from config.toml
      SNOWFLAKE_ROLE: "DEVOPS_ADMIN"       # Role from config.toml

    steps:
      # Checkout repository to access SQL files in steps folder
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Snowflake CLI using pip globally
      - name: Install Snowflake CLI
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install snowflake-cli
          echo "Snowflake CLI installed successfully"

      # Verify Snowflake CLI installation and show environment variables
      - name: Verify Snowflake CLI
        run: |
          which snow
          snow --version
          env | grep SNOWFLAKE

      # Fetch repository changes from Snowflake Git Repo with connection parameters
      - name: Fetch repository changes
        run: |
          snow git fetch "${REPO_NAME}" \
            --account ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            --user ${{ secrets.SNOWFLAKE_USER }} \
            --password ${{ secrets.SNOWFLAKE_PASSWORD }} \
            --role "DEVOPS_ADMIN" \
            --warehouse "QUICKSTART_WH"

      # Deploy pipeline by executing the steps in the deploy_parametrized_pipeline.sql file
      - name: Deploy data pipeline
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          snow git execute \
            "@${REPO_NAME}/branches/${BRANCH_NAME}/deploy_parametrized_pipeline.sql" \
            --account ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            --user ${{ secrets.SNOWFLAKE_USER }} \
            --password ${{ secrets.SNOWFLAKE_PASSWORD }} \
            --role "DEVOPS_ADMIN" \
            --warehouse "QUICKSTART_WH"


