name: Deploy data pipeline

# Action will run on pushes to selected branches
on:
  push:
    branches:
      - dev
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Change to on-prem runner for PrivateLink access

    env:
      SF_ACCOUNT: "zv20465.east-us-2.privatelink"  # PrivateLink account
      SF_USERNAME: "DEVOPS_ADMIN"
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      REPO_NAME: "quickstart_common.public.quickstart_repo"  # Ensure this is set correctly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug REPO_NAME to ensure it is properly set
      - name: Debug REPO_NAME
        run: |
          echo "Repository Name: $REPO_NAME"

      # Install dependencies, including Snowflake connector
      - name: Set up Python and install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Snowflake Connector
        run: |
          python -m pip install --upgrade pip
          python -m pip install snowflake-connector-python

      # Install Snowflake CLI GitHub Action and point to config file
      - uses: Snowflake-Labs/snowflake-cli-action@v1
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      # Update Snowflake's copy of the repository with explicit variable passing
      - name: Fetch repository changes
        run: |
          snow git fetch "$REPO_NAME" \
          --account-name "$SF_ACCOUNT" \
          --user "$SF_USERNAME" \
          --password "$SNOWFLAKE_PASSWORD"

      # Deploy pipeline with branch-specific parameters
      - name: Deploy data pipeline to ${{ github.ref_name }}
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [ "${BRANCH_NAME}" == "main" ]; then
            RETENTION_TIME=1
          elif [ "${BRANCH_NAME}" == "dev" ]; then
            RETENTION_TIME=0
          fi
          snow git execute \
            "@${REPO_NAME}/branches/${BRANCH_NAME}/deploy_parametrized_pipeline.sql" \
            --account-name ${SF_ACCOUNT} \
            --user ${SF_USERNAME} \
            --password ${{ secrets.SNOWFLAKE_PASSWORD }} \
            -D "environment='${BRANCH_NAME}'" \
            -D "retention_time=${RETENTION_TIME}"
