name: Deploy data pipeline

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: "quickstart_common.public.quickstart_repo"
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_WAREHOUSE: "QUICKSTART_WH"  # From config.toml
      SNOWFLAKE_ROLE: "DEVOPS_ADMIN"        # From config.toml

    steps:
      # Checkout repository to access SQL files in steps folder
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Snowflake CLI using pip globally
      - name: Install Snowflake CLI
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install snowflake-cli
          echo "Snowflake CLI installed successfully"

      # Verify Snowflake CLI installation and environment variables
      - name: Verify Snowflake CLI and Environment Variables
        run: |
          which snow
          snow --version
          echo "SNOWFLAKE_ACCOUNT=$SNOWFLAKE_ACCOUNT"
          echo "SNOWFLAKE_USER=$SNOWFLAKE_USER"
          echo "SNOWFLAKE_WAREHOUSE=$SNOWFLAKE_WAREHOUSE"
          echo "SNOWFLAKE_ROLE=$SNOWFLAKE_ROLE"

      # Fetch repository changes from Snowflake Git Repo
      - name: Fetch repository changes
        run: snow git fetch "${REPO_NAME}"

      # Deploy pipeline by executing the steps in the deploy_parametrized_pipeline.sql file
      - name: Deploy data pipeline
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          snow git execute \
            "@${REPO_NAME}/branches/${BRANCH_NAME}/deploy_parametrized_pipeline.sql"
