name: Deploy data pipeline

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: "quickstart_common.public.quickstart_repo"
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      # Checkout repository to access SQL files in steps folder
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Snowflake CLI GitHub Action
      - uses: Snowflake-Labs/snowflake-cli-action@v1
        with:
          cli-version: "latest"

      # Fetch repository changes from Snowflake Git Repo
      - name: Fetch repository changes
        run: snow git fetch "${REPO_NAME}"

      # Deploy pipeline by executing the steps in the deploy_parametrized_pipeline.sql file
      - name: Deploy data pipeline
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          snow git execute \
            "@${REPO_NAME}/branches/${BRANCH_NAME}/deploy_parametrized_pipeline.sql"
